api_platform:
    title: EvoltPlus API
    version: 1.0.0
    # Mercure integration, remove if unwanted
    mercure:
        include_type: true
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        multipart: ['multipart/form-data']
        jsonld: ['application/ld+json']

    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
        versions: [3]
