flysystem:
    storages:
        s3.storage:
            adapter: 'aws'
            options:
                client: '@Aws\S3\S3Client'
                bucket: '%env(AWS_S3_BUCKET)%'
                # prefix: 'uploads'   # opcional, carpeta base en el bucket
