vich_uploader:
    db_driver: orm

    metadata:
        type: attribute
        
    mappings:
       csv:
           uri_prefix: /csv
           upload_destination: s3.storage
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           directory_namer: evolt.directory_namer.product
           delete_on_remove: true

           
